version: '3.5'

services:
  xml-converter:
    image: 'xml-converter'
    build:
      context: ""
    container_name: xml-converter-container
    ports:
      - '8080:8080'
    environment:
      - DB_NAME=$DB_NAME_ENV
      - DB_USER=$DB_USER_ENV
      - DB_PASSWORD=$DB_PASSWORD_ENV
    env_file:
      - .env